export default {
	name: ' Sara Fotros',
	home: 'HOME',
	about: 'ABOUT',
	resume: 'RESUME',
	portfolio: 'PORTFOLIO',
	contact: 'CONTACT',
	hi: 'Hi, I am ',
	hi2: ' ',
	IAm: 'I am',
	desc:
		'Junior Full Stack Developer with a focus on JavaScript including React and Redux. I come from a background as a professional percussionist and instructor',
	desc2:
		'Full-stack web developer, with a background as a professional percussionist and instructor. Extensive experience as a tutor with a firm basis for problem solving whilst collaborating and actively learning with others. I enjoy taking on new challenges, and am able to combine my logical mindset, and the structured, yet creative nature that I have developed as a musician, in coding.',
	aboutme: 'ABOUT ME',
	services: 'SERVICES',
	fullname: 'Full Name',
	location: 'Location',
	skills: 'Skills',
	languages: 'Languages',
	freelance: 'Freelance',
	uk: 'London, UK',
	js: 'Ruby, Rails, JavaScript, React',
	eng: 'English & Persian',
	available: 'Available',
	downloadcv: 'DOWNLOAD CV',
	webdesign: 'Web Design',
	webdevelop: 'Web Development',
	mobileapp: 'Mobile Application',
	descdesgin:
		'Implementing user interfaces with React, React Router, and Material UI, CSS, JSS, and Bootstrap for styling. Creating responsive websites',
	descwebdev:
		'Building RESTFUL APIs with Ruby on Rails, with Postgres database. implementing MVC structure to separate concerns and facilitate the development',
	descmobApp:
		'React Native on Frontend and Rails on the Backend . A side gig project ... Comming Soon!',
	myskills: 'My Skills',
	workingSteps: [
		{
			id: -1,
			date: '',
			title: '',
			subtitle: '',
			content: '',
		},
		{
			id: 0,
			date: '2015 - 2016',
			title: 'Information Systems Engineer ',
			subtitle: 'Mortabet Rayane',
			content:
				'Information Systems Engineer for Mortabet Rayane, Information Technology Company, in Tehran, Iran. Responsible for the monitoring and maintenance of computer systems within the company as well as monitoring telecommunication systems and customer service',
		},
		{
			id: 1,
			date: '2002 - 2019',
			title: 'Professional Musician',
			subtitle: 'Percussionist',
			content:
				'I am a professional percussionist and have been performing professionally since 2002. I have performed at the national level with different ensembles in Iran, and also as part of international commissions in Iran, the UK, and globally. ●	I am a recording artist and stage performer and have been featured on numerous audio and visual projects for several popular contemporary and traditional bands including Ajam who were most prominently selected by the BBC World Service as eight acts that represent the contemporary sound of the ‘Middle East’. As part of these projects I have performed in Radio and Television broadcasts in the UK, Sweden, and the USA',
		},
		{
			id: 2,
			date: '2002 - 2019',
			title: 'Music Tutor ',
			subtitle: 'Sepahan Sina, Navaye Shahrashoob, Rock',
			content:
				'I have practiced professional tuition at various music institutes, including Sepahan Sina, Navaye Shahrashoob, Rock, and Zavieh in Iran.●	I have also provided private tuition in a one-on-one environment for students of varied ages and abilities in Esfahan, Tehran, and London.',
		},
		{
			id: -2,
			date: '',
			title: '',
			subtitle: '',
			content: '',
		},
	],
	educationalSteps: [
		{
			id: -1,
			date: '',
			title: '',
			subtitle: '',
			content: '',
		},
		{
			id: 0,
			date: '2019 - 2020',
			title: 'Software engineering',
			subtitle: 'Flatiron, London, UK',
			content:
				'Full Stack Web Development, Ruby on Rails, React, and JavaScript',
		},
		{
			id: 1,
			date: '2017-2018',
			title: 'Master of Business Administration in Art',
			subtitle: 'Bahar School of Management',
			content: 'Tehran, Iran',
		},
		{
			id: 2,
			date: '2001-2005',
			title: 'Bachelor of science degree in Electrical engineering ',
			subtitle: 'Azad University',
			content: 'Iran, Isfahan',
		},
		{
			id: -2,
			date: '',
			title: '',
			subtitle: '',
			content: '',
		},
	],
	workExperience: 'Work Experience',
	educationalQualification: 'Educational Qualification',
	contactme: 'CONTACT ME',
	getintouch: 'Get In Touch',
	enterYourName: 'Enter Your Name',
	enterYourEmail: 'Enter Your Email',
	enterYourSubject: 'Enter Your Subject',
	enterYourMessage: 'Enter Your Message',
	sendMessage: 'Send Message',
	namef: 'Name',
	emailf: 'Email',
	subjectf: 'Subject',
	mesgF: 'Message',
	email: 'Email',
	address: 'Address',
	phone: 'Phone',
};
