export default {
	name: ' Sara Fotros',
	home: 'HOME',
	about: 'ABOUT',
	resume: 'RESUME',
	portfolio: 'PORTFOLIO',
	contact: 'CONTACT',
	hi: 'Hi, I am ',
	hi2: ' ',
	IAm: 'I am',
	desc:
		'I am a Junior Full Stack Developer with a focus on JavaScript including React and Redux. I come from a Music and teaching Percussions background',
	desc2:
		'Full stack web developer, with a background as a professional musician and tutor. Extensive experience as a tutor with a firm basis for problem solving whilst collaborating and actively learning with others. I enjoy taking on new challenges, and am able to combine my logical mindset, and the structured, yet creative nature that I have developed as a musician, in coding.',
	aboutme: 'ABOUT ME',
	services: 'SERVICES',
	fullname: 'Full Name',
	location: 'Location',
	skills: 'Skills',
	languages: 'Languages',
	freelance: 'Freelance',
	uk: 'London, UK',
	js: 'Ruby, Rails, JavaScript, React',
	eng: 'English & Persian',
	available: 'Available',
	downloadcv: 'DOWNLOAD CV',
	webdesign: 'Web Design',
	webdevelop: 'Web Development',
	mobileapp: 'Mobile Application',
	descdesgin:
		'Built a RESTFUL API with Ruby on the Rails, with endpoints for users and points. Frontend built with JavaScript and React, and Router',
	descwebdev:
		'Frontend built with JavaScript and React, and React Router and Bootstrap and CSS for styling',
	descmobApp: 'React Native/Flutter/Dart... Comming Soon!',
	myskills: 'My Skills',
	workingSteps: [
		{
			id: -1,
			date: '',
			title: '',
			subtitle: '',
			content: '',
		},
		{
			id: 0,
			date: '2002 - 2019',
			title: 'Information Systems Engineer ',
			subtitle: 'Mortabet Rayane',
			content:
				'Information Systems Engineer for Mortabet Rayane, Information Technology Company, in Tehran, Iran',
		},
		{
			id: 1,
			date: '2002 - 2019',
			title: 'Musician',
			subtitle: 'Ajam',
			content:
				'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quisquam eaque autem nam nulla provident? Reiciendis alias id blanditiis eiu ee fugit. Illum ducimus voluptate corporis. saksj jdsjdks',
		},
		{
			id: 2,
			date: '2002 - 2019',
			title: 'Musician',
			subtitle: 'Ajam',
			content:
				'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quisquam eaque autem nam nulla provident? Reiciendis alias id blanditiis eiu ee fugit. Illum ducimus voluptate corporis. saksj jdsjdks',
		},
		{
			id: -2,
			date: '',
			title: '',
			subtitle: '',
			content: '',
		},
	],
	educationalSteps: [
		{
			id: -1,
			date: '',
			title: '',
			subtitle: '',
			content: '',
		},
		{
			id: 0,
			date: '2019 - 2020',
			title: 'Software engineering',
			subtitle: 'Flatiron, London, UK',
			content:
				'Full Stack Web Development, Ruby on Rails, React, and JavaScript',
		},
		{
			id: 1,
			date: '2017-2018',
			title: 'Master of Business Administration in Art',
			subtitle: 'Bahar School of Management',
			content: 'Tehran',
		},
		{
			id: 2,
			date: '2015',
			title: 'Bachelor of science degree in Electrical engineering ',
			subtitle: '	Azad University',
			content: 'Iran, Isfahan',
		},
		{
			id: -2,
			date: '',
			title: '',
			subtitle: '',
			content: '',
		},
	],
	workExperience: 'Work Experience',
	educationalQualification: 'Educational Qualification',
	contactme: 'CONTACT ME',
};
