export default {
	name: ' Sara Fotros',
	home: 'HOME',
	about: 'ABOUT',
	resume: 'RESUME',
	portfolio: 'PORTFOLIO',
	contact: 'CONTACT',
	hi: 'Hi, I am ',
	hi2: ' ',
	IAm: 'I am',
	desc: 'I am a Junior Full Stack Developer with a focus on JavaScript including React and Redux. I come from a Music and teaching Percussions background',
	desc2: 'Full stack web developer, with a background as a professional musician and tutor. Extensive experience as a tutor with a firm basis for problem solving whilst collaborating and actively learning with others. I enjoy taking on new challenges, and am able to combine my logical mindset, and the structured, yet creative nature that I have developed as a musician, in coding.',
	aboutme: 'ABOUT ME',
	services: 'SERVICES',
	fullname: 'Full Name',
	location: 'Location',
	skills: 'Skills',
	languages: 'Languages',
	freelance: 'Freelance',
	uk: 'London, UK',
	js: 'Ruby, Rails, JavaScript, React',
	eng: 'English & Persian',
	available: 'Available',
	downloadcv: 'DOWNLOAD CV',
};
